### ISSUE TITLE
Slide and/or Tap may not work as intended when an ancestor supports similar gestures

### ISSUE THREAD

**Issue by thesensibledev** [suragch/audio_video_progress_bar#44]
The gesture recognition of the ProgressBar may conflict with other (usually ancestor) widgets trying to recognize similar gestures.
Also see #39 , #31, #23

I have created a replicated this issue in an stand-alone project [here](https://github.com/thesensibledev/gesture_playground).  The gif below demonstrates the issue

The underlying source of this problem is that when multiple gesture recognizers compete in the same space, the framework resolves the final gesture / widget using a sophisticated logic.  Read [GestureArenaManager](https://api.flutter.dev/flutter/gestures/GestureArenaTeam-class.html). Also see [Gesture Disambugation](https://flutter.dev/gestures/#gesture-disambiguation). 

The first step is to level the competing field by using consistent gesture settings (i.e. Slop values) through out. We may do this by using `MediaQuery.of(context).gestureSettings`. This is sufficient to get our drag performing well with the competition.

### Next step is to understand how Tap competes with Drag.  
---
When there is just a single gesture recognizer that is a DragRecognizer, there is no competition and the drag wins by default.  But when there are widgets competing for both taps and  drags, the framework has to do more work to identify the recognizer that will win the gesture.  There are a couple of ways to tackle this

1) We let our HorizontalDragGestureRecognizer take absolute precedence - see #29 . The consequence is there is no longer a differentiator between different gestures - Tap, Double Tap, Drag - they are all treated as Drag

2) We handle Taps and Drags separately in it's own gesture recognizer and re-use as much code as possible between the two. This is how the framework's [Slider](https://api.flutter.dev/flutter/material/Slider-class.html) class works. 

3) Instead of creating an exclusive Tap gesture recognizer, we handle a tap down with a [GestureDragDownCallback](https://api.flutter.dev/flutter/gestures/GestureDragDownCallback.html)  in the HorizontalDragGestureRecognizer's  `onDown` property.  I will link an implementation of this tactic in a PR below. 

Thanks to @suragch for this wonderful widget that lays a fantastic foundation to dive deeper.
And @Hwan-seok for documenting the issue in detail in #23 

![gesture_playground](https://user-images.githubusercontent.com/111119168/191158256-690a9475-8553-4968-a2cb-90745c4e8265.gif)

**Comment by suragch** [comment]
@thesensibledev I'm super impressed with your explanation and the PR to solve the problem. You understand the gesture issues better than I do, but your explanation helped me to get a little closer to your understanding.

The way you handled this makes me trust your solution, so I'm going to merge your PR. Before publishing the next version to Pub, though, I'd like to have some sort of test. My tests in the test folder aren't great. They only confirm that the API exists. I've been using the example app as a testing ground for the new features and fixes. (Some day it would be nice to automate those tests as widget or integration tests rather than running them manually every time but that's a different issue.) What could we do in the sample app to test this PR? Maybe we could add a `PageView` like in your stand-alone project. The second page could be anything for now. In the future is could be a minimal example (as opposed to the bloated example in the current project) or it could be an example of the progress bar used in conjunction with a video (though that might be better as a separate example project). What are your thoughts?

**Comment by suragch** [comment]
In what way will `MediaQuery` affect the tests?

**Comment by thesensibledev** [comment]
> In what way will `MediaQuery` affect the tests?

PR #45 introduces a `MediaQuery.of(context).gestureSettings` - which essentially implies that we apply gestureSettings according to the default value for _THAT_ device. This is the way framework classes such as Slider function as well.

This, however, introduces a new issue in testing - by default tests don't provide an ancestor widget with with the gestureSettings. Hence instead of pumping the widget by itself we need to pump it as a child of a widget that can provide with the required MediaQuery (such as a MaterialApp)

**Comment by suragch** [comment]
Ah, that makes sense! I'm learning a lot through this.

Wrapping the widget in the tests shouldn't be a problem in my opinion since that doesn't affect the developer experience.

**Comment by thesensibledev** [comment]
If we narrow our vision to just MediaQuery, an easy way would be to wrap the test widget like this -
 ```dart
 Widget withMediaQuery({required Widget testWidget}) {
    return MediaQuery(
      data: MediaQueryData.fromWindow(window),
      child: testWidget,
    );
  }
```
But intuitively MaterialApp comes closer to simulating the actual environment in which the widget is used, so I will prefer to wrap the widget inside MaterialApp (also considering, future testing enhancements/opportunities)

**Comment by suragch** [comment]
I've described the request to handle tap events separately in #51. If I've misunderstood anything, please comment.
