### ISSUE TITLE
[bug] buffer value cross out the progress bar 

### ISSUE THREAD

**Issue by Abolfazl-MI** [suragch/audio_video_progress_bar#59]
Hi , I have feature to play short voice in my app if even there is one or 2 seconds of audio , but when buffer value download and want to display on screen the buffer cross it out this is picture of it .
 
![issuse](https://github.com/suragch/audio_video_progress_bar/assets/80602236/ab38c800-797a-4138-9fba-7d9f0e98042d)

**Comment by suragch** [comment]
That's very strange. I never tested this on small values so this could be an edge case. Could you tell me the values for position, buffered, and total?

**Comment by suragch** [comment]
This is due to giving the progress bar an invalid value for the `buffered` parameter. `buffered` should never be greater than the `total` duration. Maybe the widget should throw an error, but for now I just clamped `buffered` (and `progress`) between 0 and `total`. You can upgrade to version 2.0.0 to get the changes.
