### ISSUE TITLE
Duration texts on the Progress Bar don't scale based on device text scaling factor

### ISSUE THREAD

**Issue by stutid** [suragch/audio_video_progress_bar#61]
Hello,
The `progress` and `total` duration of `ProgressBar` don't change their text scales based on the device text scale factor. 

Is it possible to add text scaling?

**Comment by suragch** [comment]
Yes, this is a bug that should be fixed. I'm not sure when I'll get to it, but hopefully before too long. PRs welcome.

**Comment by suragch** [comment]
This is now fixed in version 2.0.1. Thank you for letting me know about the bug.

Before:

<img width="838" alt="Screenshot 2023-10-11 at 09 40 43" src="https://github.com/suragch/audio_video_progress_bar/assets/10300220/9893b2cc-650f-41ed-8f0a-5967e07fa921">

After:

<img width="836" alt="Screenshot 2023-10-11 at 10 04 36" src="https://github.com/suragch/audio_video_progress_bar/assets/10300220/b27bf93a-3b2b-4217-a62a-3a15ae3a80ca">
